apiVersion: v1
kind: ServiceAccount
metadata:
  name: threat-detector
  namespace: security-soc
  labels:
    app: threat-detector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-scanner
  namespace: security-soc
  labels:
    app: security-scanner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: threat-detector-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["security.istio.io"]
  resources: ["authorizationpolicies"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: threat-detector-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: threat-detector-role
subjects:
- kind: ServiceAccount
  name: threat-detector
  namespace: security-soc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: security-soc
  name: security-scanner-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: security-scanner-binding
  namespace: security-soc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: security-scanner-role
subjects:
- kind: ServiceAccount
  name: security-scanner
  namespace: security-soc